Fiscal policy stream
upmacrolab/upmacrolab.github.io pull request #15
Opened 2024-05-17 08:55 UTC by Tumisang-Loate

First draft of the workstream template. I made several changes as indicated:
- The stream summary
- Added images for each paper
- Summary of each paper

2024-05-17 09:00 UTC, upmacrolab commented
Looks good

2024-05-20 11:23 UTC, upmacrolab requested changes
Please consolidate fiscal.md and fiscal1.md into a single file called "fiscal.md". Gave it a quick glance but I didn't see the difference. Jekyll will read fiscal.md. Thanks

2024-05-22 12:01 UTC, Tumisang-Loate commented
I have deleted the fiscal1.md, it was a draft for the fiscal.md.

2024-06-05 04:10 UTC, upmacrolab approved these changes

2024-06-05 04:14 UTC, merged